export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'

export const ERROR = 'ERROR'

export const CONFIGURE = 'CONFIGURE'
export const CONFIGURE_RETURNED = 'CONFIGURE_RETURNED'

export const GET_POOL_BALANCES = 'GET_POOL_BALANCES'
export const POOL_BALANCES_RETURNED = 'POOL_BALANCES_RETURNED'

export const DEPOSIT_POOL = 'DEPOSIT_POOL'
export const DEPOSIT_POOL_RETURNED = 'DEPOSIT_POOL_RETURNED'

export const WITHDRAW_POOL = 'WITHDRAW_POOL'
export const WITHDRAW_POOL_RETURNED = 'WITHDRAW_POOL_RETURNED'

export const EXCHANGE_POOL = 'EXCHANGE_POOL'
export const EXCHANGE_POOL_RETURNED = 'EXCHANGE_POOL_RETURNED'

export const GET_EXCHANGE_PRICE = 'GET_EXCHANGE_PRICE'
export const EXCHANGE_PRICE_RETURNED = 'EXCHANGE_PRICE_RETURNED'

export const GET_WITHDRAW_PRICE = 'GET_WITHDRAW_PRICE'
export const WITHDRAW_PRICE_RETURNED = 'WITHDRAW_PRICE_RETURNED'

export const GET_DEPOSIT_PRICE = 'GET_DEPOSIT_PRICE'
export const DEPOSIT_PRICE_RETURNED = 'DEPOSIT_PRICE_RETURNED'
